### ISSUE TITLE
Update userUpdate mutation to allow for update of all fields

### ISSUE THREAD

**Issue by leahriffell** [leahriffell/Crate#99]
The FE has a form for updating: 
- name
- email
- password
- image
- description
- all address fields 
  - address line 1, address line 2, city, state, zip
- role

**Comment by ericberglund117** [comment]
It looks like we are all good up till address. We currently only have 1 input for an address, but i think we can modify that to fit your 5 columns. We also don't include role.

**Comment by leahriffell** [comment]
@ericberglund117 ok maybe role shouldn't be editable.. that would be odd. So I'll remove that one!

And would it be easy to add those separate address inputs? If we store as 1 string in the database, it's not super flexible or scalable going forward because it wouldn't be as easy to parse out data points like state, zip, etc.

**Comment by ericberglund117** [comment]
@leahriffell It would be an easy fix on our end, so no worries about that. We might need to rearrange how we are gathering that data in our state, but again, not too difficult. So whatever is easiest and doable for y'all, we can accommodate that. We are used to having to structure our data based on the BE structures!
